version: '3'
services:
  app:
    image: mesohealth/backend:v1.0.0
    restart: always
    environment:
      - MESO_DATABASE_PASSWORD=$MESO_DATABASE_PASSWORD
      - ROLLBAR_ACCESS_TOKEN=$ROLLBAR_ACCESS_TOKEN
      - ROLLBAR_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - dragonfly-data:/app/public/dragonfly/docker
  db:
    image: postgres:9.6.9-alpine
    restart: always
    environment:
      - POSTGRES_USER=meso
      - POSTGRES_DB=meso
      - POSTGRES_PASSWORD=$MESO_DATABASE_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
  metabase:
    image: metabase/metabase
    restart: always
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - "5000:3000"
    volumes:
      - metabase-data:/metabase-data
volumes:
  db-data:
  dragonfly-data:
  metabase-data:
